### PR TITLE
synaptics_drivers_s3706.c: memory leak fix in synaptics_get_touch_points

### PR DESCRIPTION
**Pull request by gubatron**
Also indent fix on the same function.

### CODE REVIEW

**Comment by edrose** [comment]
Out of interest, is this related to the ghost touch issue?

**Comment by gubatron** [comment]
no clue, perhaps.

### Does anybody know who's the maintainer?

The header of these files refers to "Tong.han@bsp.group.tp" but it seems the email address is invalid.

**Comment by gubatron** [comment]
@hecaiqiang  do you know who's the maintainer of this file? I found a memory leak and Tong.han@bsp.group.tp is an invalid email address for the maintainer on the headers. Perhaps you can help get this memory leak fix merged. Cheers

**Comment by hecaiqiang** [comment]
@gubatron 
Yes, I will try contact with the maintainer, and check the memory leak issue, thanks very much for your help.
Best wishes.

**Pull request closed without merging**
